### PR TITLE
add source from base64

### PR DESCRIPTION
**Pull request by emanuele-em**
- Source also from base64 string

### CODE REVIEW

**Comment by Lurk** [comment]
Hey @emanuele-em, thank you for the contribution. 
Can you please add a test case to https://github.com/Lurk/cloudinary_rs/blob/main/src/tests/mod.rs?

**Comment by emanuele-em** [comment]
@Lurk test added :)

**Comment by Lurk** [comment]
@emanuele-em Hey, I am cycling through Lapland now. I will review your changes when I am back in civilization. 

TY for your contribution, and sorry for the delay.

**Comment by emanuele-em** [comment]
> @emanuele-em Hey, I am cycling through Lapland now. I will review your changes when I am back in civilization.
> 
> TY for your contribution, and sorry for the delay.

no hurry! watch out for polar bears, I need this merge 🐻‍❄️

**Comment by Lurk** [comment]
@emanuele-em Hey, thank you for the contribution and for waiting. 
Check out the latest version at https://github.com/Lurk/cloudinary_rs/releases/tag/0.5.0 or https://crates.io/crates/cloudinary

**Pull request merged**
